In [1]:
import cv2
import skimage
import matplotlib.pyplot as plt
import numpy as np

In [12]:
def create_gaussian_filter(theta, sigma_x, sigma_y, size, filter_type='edge'):
    # Create a grid of (x, y) coordinates
    x = np.linspace(-size//2+1, size//2, size)
    y = np.linspace(-size//2+1, size//2, size)
    x, y = np.meshgrid(x, y)
    print(x)
    print(y)

    # Rotate the coordinates
    x_rot = x * np.cos(theta) + y * np.sin(theta)
    y_rot = -x * np.sin(theta) + y * np.cos(theta)
    
    # Calculate the Gaussian function
    g = np.exp(-0.5 * (x_rot**2 / sigma_x**2 + y_rot**2 / sigma_y**2))
    g /= (2 * np.pi * sigma_x * sigma_y)
    
    if filter_type == 'edge':
        # First derivative (edge)
        dG_dx = -x_rot / (sigma_x**2) * g
        dG_dy = -y_rot / (sigma_y**2) * g
        return dG_dx, dG_dy
    elif filter_type == 'bar':
        # Second derivative (bar)
        d2G_dx2 = (x_rot**2 / sigma_x**4 - 1 / sigma_x**2) * g
        d2G_dy2 = (y_rot**2 / sigma_y**4 - 1 / sigma_y**2) * g
        return d2G_dx2, d2G_dy2
    else:
        raise ValueError("Unknown filter type. Use 'edge' or 'bar'.")

# Example usage:
theta = 0  # No rotation
sigma_x = 1
sigma_y = 2
size = 7
filter_type = 'edge'

edge_x, edge_y = create_gaussian_filter(theta, sigma_x, sigma_y, size, filter_type)

[[-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]]
[[-3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.]]
