In [2]:
import cv2
import skimage
import matplotlib.pyplot as plt
import numpy as np

In [6]:
def create_gaussian_filter(theta, sigma_x, sigma_y, size, filter_type='edge'):
    # Create a grid of (x, y) coordinates
    x = np.linspace(-size//2+1, size//2, size)
    y = np.linspace(-size//2+1, size//2, size)
    x, y = np.meshgrid(x, y)
    print(x)
    print(y)

    # Rotate the coordinates
    x_rot = x * np.cos(theta) + y * np.sin(theta)
    y_rot = -x * np.sin(theta) + y * np.cos(theta)
    
    # Calculate the Gaussian function f(xrot,sigmax)*f(yrot,sigmay)
    fx = np.exp(-0.5 * (x_rot**2 / sigma_x**2))/(np.sqrt(2 * np.pi) * sigma_x)
    fy = np.exp(-0.5 * (y_rot**2 / sigma_y**2))/(np.sqrt(2 * np.pi) * sigma_y)
    if filter_type == 'edge':
        # First derivative (edge)
        dG_dx = fy*fx*(-x_rot/sigma_x**2)
        dG_dy = fx*fy*(-y_rot/sigma_y**2)
        return dG_dx, dG_dy
    elif filter_type == 'bar':
        # Second derivative (bar)
        d2G_dx2 = fy*fx*((x_rot-sigma_x**2)/sigma_x**4)
        d2G_dy2 = fx*fy*((y_rot-sigma_y**2)/sigma_y**4)
        return d2G_dx2, d2G_dy2
    else:
        raise ValueError("Unknown filter type. Use 'edge' or 'bar'.")

# Example usage:
theta = 0  # No rotation
sigma_x = 1
sigma_y = 2
size = 7
filter_type = 'edge'

edge_x, edge_y = create_gaussian_filter(theta, sigma_x, sigma_y, size, filter_type)

print(edge_x)
print(edge_y)

[[-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]]
[[-3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.]]
[[ 0.000861    0.00699278  0.01566973 -0.         -0.01566973 -0.00699278
  -0.000861  ]
 [ 0.00160857  0.01306423  0.02927492 -0.         -0.02927492 -0.01306423
  -0.00160857]
 [ 0.00234045  0.01900835  0.04259475 -0.         -0.04259475 -0.01900835
  -0.00234045]
 [ 0.00265208  0.02153928  0.04826618 -0.         -0.04826618 -0.02153928
  -0.00265208]
 [ 0.00234045  0.01900835  0.04259475 -0.         -0.04259475 -0.01900835
  -0.00234045]
 [ 0.00160857  0.01306423  0.02927492 -0.         -0.02927492 -0.01306423
  -0.00160857]
 [ 0.000861    0.00699278  0.0

In [ ]:
# Question 2
